### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by reinkepatrick** [IoT-Lab-Minden/mailify#14]
- [x]  Unittests C++ code
- [ ]  Clean up code
- [x]  Magic numbers removed
- [ ]  Sequence diagram
- [x]  Class diagram
- [x] Activity diagram - Frontend
- [x] Activity diagram - Controller
- [x]  Frontend description
- [x]  REST-API description
- [x]  Mainfile description
